trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

strategy:
  matrix:
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- bash: |
    echo ">>> Compile vscode-vue-custom-editor"
    npm ci && npm compile
    echo ">>> Compiled vscode-vue-custom-editor"
    echo ">>> Run sample integration test"
    npm test
  displayName: Run Tests
