on:
  release:
    types:
      - created

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install latest npm
      run: npm install -g npm@latest
    - name: Check npm version
      run: npm -v
    - name: Install project dependencies
      run: npm ci
    - name: Run tests
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: Run tests
      run: npm test
      if: runner.os != 'Linux'
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install latest npm
      run: npm install -g npm@latest
    - name: Check npm version
      run: npm -v
    - name: Install project dependencies
      run: npm ci
    - name: Install media dependencies
      run: cd media && npm ci && cd ..
    - name: Publish
      if: success()
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
